/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LandingImport } from './routes/_landing'
import { Route as AuthImport } from './routes/_auth'
import { Route as AppImport } from './routes/_app'
import { Route as AdminImport } from './routes/_admin'
import { Route as AuthSignupImport } from './routes/_auth/signup'
import { Route as AuthSigninImport } from './routes/_auth/signin'
import { Route as AppSafetySafetyImport } from './routes/_app/_safety/safety'
import { Route as AppAboutAboutImport } from './routes/_app/_about/about'
import { Route as AppDriverDriverImport } from './routes/_app/_Driver/driver'

// Create Virtual Routes

const AppIndexLazyImport = createFileRoute('/_app/')()
const AppDashboardLazyImport = createFileRoute('/_app/dashboard')()
const AdminDashboardLazyImport = createFileRoute('/_admin/dashboard')()

// Create/Update Routes

const LandingRoute = LandingImport.update({
  id: '/_landing',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/_admin',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexLazyRoute = AppIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/index.lazy').then((d) => d.Route))

const AppDashboardLazyRoute = AppDashboardLazyImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/dashboard.lazy').then((d) => d.Route),
)

const AdminDashboardLazyRoute = AdminDashboardLazyImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/_admin/dashboard.lazy').then((d) => d.Route),
)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSigninRoute = AuthSigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)

const AppSafetySafetyRoute = AppSafetySafetyImport.update({
  id: '/_safety/safety',
  path: '/safety',
  getParentRoute: () => AppRoute,
} as any)

const AppAboutAboutRoute = AppAboutAboutImport.update({
  id: '/_about/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)

const AppDriverDriverRoute = AppDriverDriverImport.update({
  id: '/_Driver/driver',
  path: '/driver',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LandingImport
      parentRoute: typeof rootRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninImport
      parentRoute: typeof AuthImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof AuthImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardLazyImport
      parentRoute: typeof AdminImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/_Driver/driver': {
      id: '/_app/_Driver/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof AppDriverDriverImport
      parentRoute: typeof AppImport
    }
    '/_app/_about/about': {
      id: '/_app/_about/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutAboutImport
      parentRoute: typeof AppImport
    }
    '/_app/_safety/safety': {
      id: '/_app/_safety/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof AppSafetySafetyImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AdminRouteChildren {
  AdminDashboardLazyRoute: typeof AdminDashboardLazyRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardLazyRoute: AdminDashboardLazyRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppDashboardLazyRoute: typeof AppDashboardLazyRoute
  AppIndexLazyRoute: typeof AppIndexLazyRoute
  AppDriverDriverRoute: typeof AppDriverDriverRoute
  AppAboutAboutRoute: typeof AppAboutAboutRoute
  AppSafetySafetyRoute: typeof AppSafetySafetyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardLazyRoute: AppDashboardLazyRoute,
  AppIndexLazyRoute: AppIndexLazyRoute,
  AppDriverDriverRoute: AppDriverDriverRoute,
  AppAboutAboutRoute: AppAboutAboutRoute,
  AppSafetySafetyRoute: AppSafetySafetyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LandingRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard': typeof AppDashboardLazyRoute
  '/': typeof AppIndexLazyRoute
  '/driver': typeof AppDriverDriverRoute
  '/about': typeof AppAboutAboutRoute
  '/safety': typeof AppSafetySafetyRoute
}

export interface FileRoutesByTo {
  '': typeof LandingRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard': typeof AppDashboardLazyRoute
  '/': typeof AppIndexLazyRoute
  '/driver': typeof AppDriverDriverRoute
  '/about': typeof AppAboutAboutRoute
  '/safety': typeof AppSafetySafetyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_landing': typeof LandingRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_admin/dashboard': typeof AdminDashboardLazyRoute
  '/_app/dashboard': typeof AppDashboardLazyRoute
  '/_app/': typeof AppIndexLazyRoute
  '/_app/_Driver/driver': typeof AppDriverDriverRoute
  '/_app/_about/about': typeof AppAboutAboutRoute
  '/_app/_safety/safety': typeof AppSafetySafetyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/signin'
    | '/signup'
    | '/dashboard'
    | '/'
    | '/driver'
    | '/about'
    | '/safety'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/signin'
    | '/signup'
    | '/dashboard'
    | '/'
    | '/driver'
    | '/about'
    | '/safety'
  id:
    | '__root__'
    | '/_admin'
    | '/_app'
    | '/_auth'
    | '/_landing'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_admin/dashboard'
    | '/_app/dashboard'
    | '/_app/'
    | '/_app/_Driver/driver'
    | '/_app/_about/about'
    | '/_app/_safety/safety'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  LandingRoute: typeof LandingRoute
}

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  LandingRoute: LandingRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_admin",
        "/_app",
        "/_auth",
        "/_landing"
      ]
    },
    "/_admin": {
      "filePath": "_admin.tsx",
      "children": [
        "/_admin/dashboard"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/dashboard",
        "/_app/",
        "/_app/_Driver/driver",
        "/_app/_about/about",
        "/_app/_safety/safety"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/signin",
        "/_auth/signup"
      ]
    },
    "/_landing": {
      "filePath": "_landing.tsx"
    },
    "/_auth/signin": {
      "filePath": "_auth/signin.tsx",
      "parent": "/_auth"
    },
    "/_auth/signup": {
      "filePath": "_auth/signup.tsx",
      "parent": "/_auth"
    },
    "/_admin/dashboard": {
      "filePath": "_admin/dashboard.lazy.tsx",
      "parent": "/_admin"
    },
    "/_app/dashboard": {
      "filePath": "_app/dashboard.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/": {
      "filePath": "_app/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/_Driver/driver": {
      "filePath": "_app/_Driver/driver.tsx",
      "parent": "/_app"
    },
    "/_app/_about/about": {
      "filePath": "_app/_about/about.tsx",
      "parent": "/_app"
    },
    "/_app/_safety/safety": {
      "filePath": "_app/_safety/safety.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
